name: Release canary

on:
  push:
    branches-ignore:
      - main (remove comment when ready for stable release)
      - 'changeset-release/main'

jobs:
  release-canary:
    name: Canary
    uses: primer/.github/.github/workflows/release_canary.yml@v1.0.0
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
