name: Release stable

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    uses: primer/.github/.github/workflows/release.yml@v1.0.0
    secrets:
      gh_token: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
